#
# LICENSE UPL 1.0
#
# Copyright (c) 2018, 2020 Oracle and/or its affiliates.
#
# Since: July, 2018
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle database Vagrant virtual machine.
# Optional plugins:
#     vagrant-env (use .env files for configuration)
#     vagrant-proxyconf (if you don't have direct access to the Internet)
#         see https://github.com/tmatilai/vagrant-proxyconf for configuration
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

# -*- mode: ruby -*-
# vi: set ft=ruby :

#VAGRANT_LOG=debug

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Box metadata location and box name
BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
BOX_NAME = "oraclelinux/7"

# UI object for printing information
ui = Vagrant::UI::Prefixed.new(Vagrant::UI::Colored.new, "vagrant")

# Define constants
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use vagrant-env plugin if available
  if Vagrant.has_plugin?("vagrant-env")
    config.env.load(".env.local", ".env") # enable the plugin
  end

  # VM name
  VM_NAME = default_s('VM_NAME', 'oipa-vagrant')

  # Memory for the VM 
  VM_MEMORY = default_i('VM_MEMORY', 8192) 

  # VM time zone
  # If not specified, will be set to match host time zone (if possible)
  VM_SYSTEM_TIMEZONE = default_s('VM_SYSTEM_TIMEZONE', host_tz)

  # Oracle base directory
  VM_ORACLE_BASE = default_s('VM_ORACLE_BASE', '/opt/oracle')

  # Oracle home directory
  VM_ORACLE_HOME = default_s('VM_ORACLE_HOME', '/opt/oracle/product/19c/dbhome_1')

  # Oracle SID
  VM_ORACLE_SID = default_s('VM_ORACLE_SID', 'ORCLCDB')

  # PDB name
  VM_ORACLE_PDB = default_s('VM_ORACLE_PDB', 'ORCLPDB1')

  # Database character set
  VM_ORACLE_CHARACTERSET = default_s('VM_ORACLE_CHARACTERSET', 'AL32UTF8')

  # Oracle Database edition
  # Valid values are 'EE' for Enterprise Edition or 'SE2' for Standard Edition 2
  VM_ORACLE_EDITION = default_s('VM_ORACLE_EDITION', 'EE')

  # Listener port
  VM_LISTENER_PORT = default_i('VM_LISTENER_PORT', 1521)

  # EM Express port
  VM_EM_EXPRESS_PORT = default_i('VM_EM_EXPRESS_PORT', 5500)

  # Oracle Database password for SYS, SYSTEM and PDBADMIN accounts
  # If left blank, the password will be generated automatically
  VM_ORACLE_PWD = default_s('VM_ORACLE_PWD', '')

  # Oracle Middleware home directory
  VM_MW_HOME = default_s('VM_MW_HOME','/opt/oracle/middleware')
  VM_MW_DOMAIN = default_s('VM_MW_DOMAIN','oipa')
  VM_WLS_PORT_ADMIN = default_s('VM_WLS_PORT_ADMIN',7001)
  VM_WLS_OIPA_PORT = default_s('VM_WLS_OIPA_PORT',10001)
  VM_WLS_PALETTECONFIG_PORT = default_s('VM_WLS_PALETTECONFIG_PORT',11001)
  VM_WLS_OIPA_SSLPORT = default_s('VM_WLS_OIPA_PORT',10002)
  VM_WLS_PALETTECONFIG_SSLPORT = default_s('VM_WLS_PALETTECONFIG_PORT',11002)
  
  # JDK Version
  VM_JDK = default_s('VM_JDK','8u311')
  VM_JAVA_PATH = default_s('VM_JAVA_PATH','/usr/java/jdk1.8.0_311-amd64')

  # WLS Version
  VM_WLS = default_s('VM_WLS','12.2.1.4.0')

  # OIPA database users
  VM_DB_USER_OIPA = default_s('VM_DB_USER_OIPA','oipa')
  VM_DB_USER_IVS = default_s('VM_DB_USER_IVS','oipaivs')

  # OIPA components
  VM_OIPA_URL_ASPECTJ = default_s('VM_OIPA_URL_ASPECTJ','https://www.eclipse.org/downloads/download.php?file=/tools/aspectj/aspectj-1.8.10.jar&mirror_id=1135')
  VM_OIPA_URL_LOG4J = default_s('VM_OIPA_URL_LOG4J','https://archive.apache.org/dist/logging/log4j/1.2.17/log4j-1.2.17.jar')
end

# Convenience methods
def default_s(key, default)
  ENV[key] && ! ENV[key].empty? ? ENV[key] : default
end

def default_i(key, default)
  default_s(key, default).to_i
end

def host_tz
  # get host time zone for setting VM time zone
  # if host time zone isn't an integer hour offset from GMT, fall back to UTC
  offset_sec = Time.now.gmt_offset
  if (offset_sec % (60 * 60)) == 0
    offset_hr = ((offset_sec / 60) / 60)
    timezone_suffix = offset_hr >= 0 ? "-#{offset_hr.to_s}" : "+#{(-offset_hr).to_s}"
    'Etc/GMT' + timezone_suffix
  else
    'UTC'
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
  config.vm.define VM_NAME
  
  # Provider-specific configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = VM_MEMORY
    v.name = VM_NAME
  end
  config.vm.provider :libvirt do |v|
    v.memory = VM_MEMORY
  end

  # add proxy configuration from host env - optional
  if Vagrant.has_plugin?("vagrant-proxyconf")
    ui.info "Getting Proxy Configuration from Host..."
    has_proxy = false
    ["http_proxy", "HTTP_PROXY"].each do |proxy_var|
      if proxy = ENV[proxy_var]
        ui.info "HTTP proxy: " + proxy
        config.proxy.http = proxy
        has_proxy = true
        break
      end
    end

    ["https_proxy", "HTTPS_PROXY"].each do |proxy_var|
      if proxy = ENV[proxy_var]
        ui.info "HTTPS proxy: " + proxy
        config.proxy.https = proxy
        has_proxy = true
        break
      end
    end

    if has_proxy
      # Only consider no_proxy if we have proxies defined.
      no_proxy = ""
      ["no_proxy", "NO_PROXY"].each do |proxy_var|
        if ENV[proxy_var]
          no_proxy = ENV[proxy_var]
          ui.info "No proxy: " + no_proxy
          no_proxy += ","
          break
        end
      end
      config.proxy.no_proxy = no_proxy + "localhost,127.0.0.1"
    end
  else
    ["http_proxy", "HTTP_PROXY", "https_proxy", "HTTPS_PROXY"].each do |proxy_var|
      if ENV[proxy_var]
        ui.warn 'To enable proxies in your VM, install the vagrant-proxyconf plugin'
        break
      end
    end
  end

  # VM hostname
  config.vm.hostname = VM_NAME

  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: VM_LISTENER_PORT, host: VM_LISTENER_PORT
  config.vm.network "forwarded_port", guest: VM_EM_EXPRESS_PORT, host: VM_EM_EXPRESS_PORT
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.network :forwarded_port, guest: VM_WLS_PORT_ADMIN, host: VM_WLS_PORT_ADMIN, auto_correct: true    # WebLogic Console
  config.vm.network :forwarded_port, guest: VM_WLS_OIPA_PORT, host: VM_WLS_OIPA_PORT, auto_correct: true  # PAS
  config.vm.network :forwarded_port, guest: VM_WLS_PALETTECONFIG_PORT, host: VM_WLS_PALETTECONFIG_PORT, auto_correct: true  # PaletteConfig
  
  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "SYSTEM_TIMEZONE"     => VM_SYSTEM_TIMEZONE,
       "ORACLE_BASE"         => VM_ORACLE_BASE,
       "ORACLE_HOME"         => VM_ORACLE_HOME,
       "ORACLE_SID"          => VM_ORACLE_SID,
       "ORACLE_PDB"          => VM_ORACLE_PDB,
       "ORACLE_CHARACTERSET" => VM_ORACLE_CHARACTERSET,
       "ORACLE_EDITION"      => VM_ORACLE_EDITION,
       "LISTENER_PORT"       => VM_LISTENER_PORT,
       "EM_EXPRESS_PORT"     => VM_EM_EXPRESS_PORT,
       "ORACLE_PWD"          => VM_ORACLE_PWD,
       "MW_HOME" => VM_MW_HOME,
       "WLS_ADMINPORT" => VM_WLS_PORT_ADMIN,
       "WLS_OIPAPORT" => VM_WLS_OIPA_PORT,
       "WLS_PALETTECONFIGPORT" => VM_WLS_PALETTECONFIG_PORT,       
       "WLS_SSLOIPAPORT" => VM_WLS_OIPA_SSLPORT,
       "WLS_SSLPALETTECONFIGPORT" => VM_WLS_PALETTECONFIG_SSLPORT,              
       "WLS_VERSION" => VM_WLS,
       "JAVA_VERSION" => VM_JDK,
       "JAVA_PATH" => VM_JAVA_PATH,
       "MW_DOMAIN" => VM_MW_DOMAIN,
       "USER_OIPA" => VM_DB_USER_OIPA,
       "USER_IVS"  => VM_DB_USER_IVS,
       "ASPECTJ_URL" => VM_OIPA_URL_ASPECTJ,
       "LOG4J_URL" => VM_OIPA_URL_LOG4J
    }

end
